name: TrojanTO
channels:
- pytorch
dependencies:
- python=3.8.15
- pytorch=1.13.0
- cudatoolkit=11.6
- numpy
- pip
- pip:
  - gym==0.25.2
  - mujoco-py==2.1.2.14
  - numpy==1.20.3
  - torch==1.13.0
  - transformers==4.11.3
  - wandb==0.9.1
